import os
import rtconfig

# Check SDK 
SIFLI_SDK = os.getenv('SIFLI_SDK')
if not SIFLI_SDK:
    print("Please run set_env.bat in root folder of SIFLI SDK to set environment.")
    exit()
from building import *

# Prepare environment.
PrepareEnv()

################################## change rtconfig.xxx to customize build ########################################

# Add local bootloader project (with OTA install support)
_proj_root = os.path.dirname(Dir('#').abspath)
_local_bootloader = os.path.join(_proj_root, 'bootloader', 'ram_v2')
AddChildProj('bootloader', _local_bootloader, False)

# Add LCPU project (for Bluetooth)
AddLCPU(SIFLI_SDK,rtconfig.CHIP,"../src/lcpu_img.c")

# Set default compile options
SifliEnv()

TARGET = rtconfig.OUTPUT_DIR + rtconfig.TARGET_NAME + '.' + rtconfig.TARGET_EXT
# Prepare building environment
objs = PrepareBuilding(None)
env = GetCurrentEnv()

# Build application.
DoBuilding(TARGET, objs)

# Add flash table buld.
AddFTAB(SIFLI_SDK,rtconfig.CHIP)

# Generate download .bat script
GenDownloadScript(env)
